#! /bin/sh
### BEGIN INIT INFO
# Provides:          bro
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts bro
# Description:       Starts bro using start-stop-daemon
### END INIT INFO

DAEMON=/usr/local/bro/bin/broctl
NAME=bro
DESC=BroIDS
PID_FILE=/var/run/$NAME.pid
DAEMON_OPTS="start"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    $DAEMON start
    ;;
  stop)
    echo -n "Stopping $DESC: "
    $DAEMON stop
    ;;
  restart|force-reload)
    $DAEMON stop
    sleep 0.5
    $DAEMON stop
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0